### ISSUE TITLE
Question about Error failed to load WASM module due to a missing import: __wbindgen_placeholder__.__wbindgen_describe

### ISSUE THREAD

**Issue by thinhtranquoc** [otomato-gh/proxy-wasm-rust#1]
Dear @antweiss 

I am new a proxy-was-rust.  I have a question.

After clone your code. I was add some code below
1. In file Cargo.toml
`jsonwebtoken = "7"
serde = {version = "1.0", features = ["derive"] }` 

1. In file lib.js
 
`let token  = self.get_http_request_header("token");
        let header = decode_header(&token.unwrap());
        trace!("header: {:?}", header);`

But when I build and deploy docker system show error.
`Failed to load WASM module due to a missing import: __wbindgen_placeholder__.__wbindgen_describe`

Log
` [2021-09-10 03:22:42.999][7][debug][wasm] [bazel-out/k8-opt/bin/external/envoy/source/extensions/common/wasm/_virtual_includes/wasm_vm_base/extensions/common/wasm/wasm_vm_base.h:38] WasmVm created envoy.wasm.runtime.v8 now active
proxy_1        | [2021-09-10 03:22:42.999][7][debug][wasm] [external/envoy/source/extensions/common/wasm/wasm.cc:121] Base Wasm created 1 now active
proxy_1        | [2021-09-10 03:22:43.175][7][debug][wasm] [external/envoy/source/extensions/common/wasm/wasm.cc:291] ~Wasm 0 remaining active
proxy_1        | [2021-09-10 03:22:43.180][7][debug][wasm] [bazel-out/k8-opt/bin/external/envoy/source/extensions/common/wasm/_virtual_includes/wasm_vm_base/extensions/common/wasm/wasm_vm_base.h:42] ~WasmVm envoy.wasm.runtime.v8 0 remaining active
proxy_1        | [2021-09-10 03:22:43.181][7][debug][init] [external/envoy/source/common/init/watcher_impl.cc:27] ListenerImpl destroyed
proxy_1        | [2021-09-10 03:22:43.181][7][debug][init] [external/envoy/source/common/init/watcher_impl.cc:27] init manager Listener main destroyed
proxy_1        | [2021-09-10 03:22:43.184][7][critical][main] [external/envoy/source/server/server.cc:96] error initializing configuration '/etc/envoy.yaml': Failed to load WASM module due to a missing import: __wbindgen_placeholder__.__wbindgen_describe
proxy_1        | [2021-09-10 03:22:43.185][7][debug][init] [external/envoy/source/common/init/watcher_impl.cc:27] ClusterImplBase destroyed
proxy_1        | [2021-09-10 03:22:43.186][7][debug][init] [external/envoy/source/common/init/watcher_impl.cc:27] init manager Cluster web_service destroyed
proxy_1        | [2021-09-10 03:22:43.186][7][debug][grpc] [external/envoy/source/common/grpc/google_async_client_impl.cc:35] Joining completionThread
proxy_1        | [2021-09-10 03:22:43.186][11][debug][grpc] [external/envoy/source/common/grpc/google_async_client_impl.cc:68] completionThread exiting
proxy_1        | [2021-09-10 03:22:43.190][7][debug][grpc] [external/envoy/source/common/grpc/google_async_client_impl.cc:37] Joined completionThread
proxy_1        | [2021-09-10 03:22:43.190][7][debug][upstream] [external/envoy/source/common/upstream/cluster_manager_impl.cc:937] shutting down thread local cluster manager
proxy_1        | [2021-09-10 03:22:43.190][7][info][main] [external/envoy/source/server/server.cc:619] exiting
proxy_1        | [2021-09-10 03:22:43.193][7][debug][init] [external/envoy/source/common/init/watcher_impl.cc:27] init manager Server destroyed
proxy_1        | Failed to load WASM module due to a missing import: __wbindgen_placeholder__.__wbindgen_describe
`

Please help me 
Thanks u

**Comment by antweiss** [comment]
hey @thinhtranquoc 
this example was built 1,5 years ago and it worked back then. I just tried to compile it (without changes) with up-to-date rust and am now getting :
```
proxy_1        | Failed to load WASM code from /etc/myenvoyfilter.wasm
```
So it looks like maybe the newer rust version is to blame. 
The error message is very uninformative so more research is needed.
I will try to look into it over the course of the week.

**Comment by Forsworns** [comment]
I recently worked on wasm and rust, thanks for your blog and examples :). I have upgraded the dependencies and they work now. See #3.
